version: '3.3'

volumes:
  static_value:

services:

  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    # image: greytres/todobackend:latest
    restart: always
    env_file:
      - ../backend/.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    # image: greytres/todofrontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - web
      - frontend
